Repository Tomasz-Zdeb/Software-Engineering-Class-Project, pull requests merged in 2023-04, with the labels that each got.

#45 API project initialization
  API/.gitignore
  API/api/__init__.py
  API/api/routes/hello.py
  API/app.py
  API/requirements.txt
Labels: API, Sprint 4

#55 Dodaj dockerfile dla API
  API/Dockerfile
  API/app.py
Labels: CI/CD, API

#60 42-zainicjalizuj-projekt-frontendu
  .vscode/extensions.json
  FRONT/DOCS.md
  FRONT/front-app/.gitignore
  FRONT/front-app/auto-generated-doc.md
  FRONT/front-app/package-lock.json
  FRONT/front-app/package.json
  FRONT/front-app/public/favicon.ico
  FRONT/front-app/public/index.html
  FRONT/front-app/public/manifest.json
  FRONT/front-app/public/robots.txt
  FRONT/front-app/src/App.css
  FRONT/front-app/src/App.js
  FRONT/front-app/src/components/DummyComponent.js
  FRONT/front-app/src/index.css
  FRONT/front-app/src/index.js
  FRONT/front-app/src/reportWebVitals.js
  FRONT/front-app/src/setupTests.js
  FRONT/front-app/src/tests/App.test.js
  FRONT/front-app/src/tests/DummyComponent.test.js
Labels: Frontend, Sprint 8

#75 Add standard acceptance criteria
  .github/ISSUE_TEMPLATE/io-projects-standard-issue.md
Labels: Sprint 8

#76 Create io-projects-standard-issue-mini.md
  .github/ISSUE_TEMPLATE/io-projects-standard-issue-mini.md
Labels: Sprint 8, Continuous Improvement

#77 Refactor according to markdownlint default rules
  README.md
Labels: Sprint 8, Continuous Improvement

#78 Update task definition section of documentation
  README.md
Labels: Sprint 8, Continuous Improvement

#80 69 skonfiguruj pipeline GitHub actions lintujacy dokumenty markdown
  .github/workflows/markdownlint.yml
  .markdownlint.json
  DB/DOCS.md
  DB/readme.md
Labels: Sprint 8, Continuous Improvement

#82 Update ci cd documentation section
  README.md
Labels: CI/CD, Sprint 8, Continuous Improvement

#84 79-stworz-skrypt-odswiezajacy-liste-zdalnych-branchow
  README.md
  scripts/bash/refresh-git-remotes-list.sh
  scripts/windows/refresh-git-remotes-list.bat
Labels: Continuous Improvement, Sprint 9

#85 68-zmien-domyslne-favicon-w-aplikacji-frontendowej
  FRONT/front-app/public/favicon.ico
Labels: Frontend, Sprint 9

#73 Stwórz dokumentacje w pliku DOCS.md dla API
  API/DOCS.md
Labels: API, Sprint 8

#72 Skonfiguruj docker-compose
  API/Dockerfile
  API/requirements.txt
  docker-compose.yaml
Labels: CI/CD, Backend, Sprint 8
